// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NFCSystem.Data;

namespace NFCSystem.Migrations
{
    [DbContext(typeof(NFCScanContext))]
    [Migration("20190312135430_users")]
    partial class users
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NFCSystem.Models.NFCScan", b =>
                {
                    b.Property<long>("TimeStamp")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DateTime");

                    b.Property<long>("UID");

                    b.HasKey("TimeStamp");

                    b.ToTable("NFCScans");
                });
#pragma warning restore 612, 618
        }
    }
}
